### ISSUE TITLE
EPICO - CRUD - Cliente

### ISSUE THREAD

**Issue by robsonjunior1994** [devs4fun/HubPro#14]
# Não code direto na main, abra uma branch.

### obs.: 
- Devemos usar interface para o Service e Repository e utilizar o padrão de injeção de dependência 
- Cada implementação deve ser acompanhada de teste unitário

- [ ] 1 - [Criar modelo do cliente](https://github.com/devs4fun/HubPro/issues/4)
- [ ] 2 - [Criar fluxo de Create](https://github.com/devs4fun/HubPro/issues/5)
- [ ] 3 - [Criar fluxo de Read](https://github.com/devs4fun/HubPro/issues/6)
- [ ] 4 - [Criar fluxo de Update ](https://github.com/devs4fun/HubPro/issues/7)
- [ ] 5 - [Criar fluxo de Delete ](https://github.com/devs4fun/HubPro/issues/8)
